### ISSUE TITLE
Add support for a read-only host

### ISSUE THREAD

**Issue by aphistic** [efritz/deepjoy#6]
AWS and other redis clusters help with scaling by adding read replicas, so having support for that built-in would be good.  Something like WithReadHost() maybe?

**Comment by efritz** [comment]
How would this change behavior? Do you expect it to query the read host for non-mutating commands and the write host otherwise? Does this introduce a new API method?

**Comment by aphistic** [comment]
I anticipated something like: `client.Read().Do()` or something and making it up to the user to decide which commands should go to the read replicas.  If a read replica isn't provided I think client.Read() should just return the main host.

**Comment by aphistic** [comment]
Looks awesome, thanks!
